name: Task6
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  Task6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: git checkout task6 | cmake . | make C | cd ..
